header = [
    { title = "About", href="/about" },
    { title = "Attend", href="/attend" }, 
    { title = "Sponsor", href="/sponsor" },
    { title = "Schedule", href="/schedule" },
    { title = "Volunteer", href="/volunteer" },
    { title = "Register", href = "/register", primary = true }
]
